In [ ]:
import torch

x = torch.rand(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor([0.4904, 0.4978, 0.0377], requires_grad=True)
tensor([2.4904, 2.4978, 2.0377], grad_fn=<AddBackward0>)
tensor(11.0623, grad_fn=<MeanBackward0>)
tensor([3.3205, 3.3304, 2.7170])
tensor(11.0623, grad_fn=<MeanBackward0>)


In [61]:
import torch

x = torch.rand(3, requires_grad=True)
with torch.no_grad():
  y = x + 2
  print(y)
z = x + 3
print(z)

tensor([2.3047, 2.6847, 2.9293])
tensor([3.3047, 3.6847, 3.9293], grad_fn=<AddBackward0>)


In [67]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(1):
  model_output = (weights*3).sum()
  print(model_output)
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_() # reset the gradient

tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


In [ ]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

In [125]:
import torch

# Simple backpropagation
weights = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(5.0)
y = torch.tensor(100.0)

for epoch in range(1000):
  y_hat = (weights*x)
  loss = (y_hat-y)**2
  
  loss.backward()
  
  # Update the weights
  with torch.no_grad():
    weights.data = weights.data - 0.01 * weights.grad
    # 0.01 is the learning rate

  weights.grad.zero_()

print(weights)

tensor(20.0000, requires_grad=True)
